### PR TITLE
fix manifest

### PR DESCRIPTION
**Pull request by vhdirk**
I could not get the demo in https://github.com/nativescript-community/ui-mapbox to work without these change

### CODE REVIEW

**Comment by keerl** [comment]
You should be able to overwrite the existing manifest by putting it in (and/or creating) the `demo-snippets/App_Resources/Android/src/main` directory. That way we don't have to modify the manifest for the actual demo project because that is a shared demo used across many plugins.

**Comment by vhdirk** [comment]
Ah, cool. that works, indeed.

**Comment by vhdirk** [comment]
Still, `android:exported="true"` is needed though. It will not merge manifests if that's not present, it seems.

**Comment by keerl** [comment]
That doesn't make sense, it just does a straight-up copy of the file. I don't see a reason why that wouldn't work. Have you done a `ns clean` and tried running it again? It might need a fresh re-copy if it has been changed.

**Comment by vhdirk** [comment]
I ran `npm clean`, `ns clean` and `npm run demo.ng.clean`; none of which do the trick. Did I put the AndroidManifest in the correct spot? https://github.com/nativescript-community/ui-mapbox/pull/65/files

**Comment by keerl** [comment]
Move the file up one level, it shouldn't be in the `res` directory.

**Comment by vhdirk** [comment]
Oh, thanks a lot! Not sure how it ended up in `res`.

**Pull request closed without merging**
